-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.devices
(
    id serial NOT NULL,
    device_model_id integer,
    location_id integer,
    modem_id integer,
    device_status_id integer DEFAULT 1,
    company_id integer,
    installation_date date NOT NULL,
    last_service_date date,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT devices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id serial NOT NULL,
    device_id integer,
    company_id integer,
    start_date date NOT NULL,
    end_date date,
    ownership_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    insurance boolean DEFAULT false,
    monthly_cost numeric(10, 2),
    annual_cost numeric(10, 2),
    payback_period integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    CONSTRAINT bookings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contracts
(
    id serial NOT NULL,
    company_id integer,
    contract_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    signing_date date NOT NULL,
    end_date date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    signature_data bytea,
    CONSTRAINT contracts_pkey PRIMARY KEY (id),
    CONSTRAINT contracts_contract_number_key UNIQUE (contract_number)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id serial NOT NULL,
    device_id integer,
    product_id integer,
    quantity bigint NOT NULL,
    minimum_stock bigint NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (id),
    CONSTRAINT inventory_device_id_product_id_key UNIQUE (device_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contact_email character varying(50) COLLATE pg_catalog."default",
    contact_phone character varying(18) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT companies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_methods
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
    CONSTRAINT payment_methods_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.device_models
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    device_type_id integer,
    description text COLLATE pg_catalog."default",
    CONSTRAINT device_models_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.modems
(
    id serial NOT NULL,
    brand character varying(20) COLLATE pg_catalog."default" NOT NULL,
    serial_number character varying(15) COLLATE pg_catalog."default" NOT NULL,
    provider character varying(50) COLLATE pg_catalog."default",
    balance numeric(10, 2) DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT modems_pkey PRIMARY KEY (id),
    CONSTRAINT modems_serial_number_key UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS public.services
(
    id serial NOT NULL,
    device_id integer,
    service_date date NOT NULL,
    work_description text COLLATE pg_catalog."default",
    issues text COLLATE pg_catalog."default",
    user_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(18) COLLATE pg_catalog."default",
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_id integer,
    company_id integer,
    language character varying(5) COLLATE pg_catalog."default" DEFAULT 'en'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id serial NOT NULL,
    device_id integer,
    product_id integer,
    sale_date_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    payment_method_id integer,
    CONSTRAINT sales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id serial NOT NULL,
    device_id integer,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    date_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.device_statuses
(
    id serial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    color_code character varying(7) COLLATE pg_catalog."default",
    CONSTRAINT device_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT device_statuses_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.device_types
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT device_types_pkey PRIMARY KEY (id),
    CONSTRAINT device_types_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(100) COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    sales_popularity numeric(5, 2) DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    device_id integer,
    user_id integer,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    priority integer DEFAULT 1,
    date_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    confirmed boolean DEFAULT false,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    id serial,
    installation_address text NOT NULL,
    place_description character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.devices
    ADD CONSTRAINT fk_companies FOREIGN KEY (company_id)
    REFERENCES public.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_devices_company
    ON public.devices(company_id);

ALTER TABLE IF EXISTS public.devices
    ADD CONSTRAINT fk_device_models FOREIGN KEY (device_model_id)
    REFERENCES public.device_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.devices
    ADD CONSTRAINT fk_modems FOREIGN KEY (modem_id)
    REFERENCES public.modems (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.devices
    ADD CONSTRAINT fk_device_statuses FOREIGN KEY (device_status_id)
    REFERENCES public.device_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_devices_status
    ON public.devices(device_status_id);

ALTER TABLE IF EXISTS public.devices
    ADD CONSTRAINT fk_locations FOREIGN KEY (location_id)
    REFERENCES public.locations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_companies FOREIGN KEY (company_id)
    REFERENCES public.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.contracts
    ADD CONSTRAINT fk_companies FOREIGN KEY (company_id)
    REFERENCES public.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_inventory_device
    ON public.inventory(device_id);

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_products FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.device_models
    ADD CONSTRAINT fk_device_types FOREIGN KEY (device_type_id)
    REFERENCES public.device_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT fk_users FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_companies FOREIGN KEY (company_id)
    REFERENCES public.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_roles FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sales_device
    ON public.sales(device_id);

ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT fk_payment_methods FOREIGN KEY (payment_method_id)
    REFERENCES public.payment_methods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT fk_products FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_devices FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_device
    ON public.notifications(device_id);

ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_users FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;